# Generated by Django 2.2 on 2020-06-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='weigt',
            new_name='weight',
        ),
    ]
